typography_spectrum: 0.9569531218148768
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.34822305059060454
  lightness: 0.30595680023543537
  saturation: 0.794161683646962
  rhythmicContrast: 0.7515289646107703
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6783791061025113
analytics:
  google: null
  facebook: null
  twitter: null
name: baldwin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
